function odom_data = importfile(filename, dataLines)
    %IMPORTFILE Import data from a text file
    %  ODOM_DATA = IMPORTFILE(FILENAME) reads data from text file FILENAME
    %  for the default selection.  Returns the data as a table.
    %
    %  ODOM_DATA = IMPORTFILE(FILE, DATALINES) reads data for the specified
    %  row interval(s) of text file FILENAME. Specify DATALINES as a
    %  positive scalar integer or a N-by-2 array of positive scalar integers
    %  for dis-contiguous row intervals.
    %
    %  Example:
    %  odom_data = importfile("/MATLAB Drive/term_project/poses/07.txt", [1, Inf]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 25-Apr-2020 15:45:10
    
    %% Input handling
    
    % If dataLines is not specified, define defaults
    if nargin < 2
        dataLines = [1, Inf];
    end
    
    %% Setup the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 12);
    
    % Specify range and delimiter
    opts.DataLines = dataLines;
    opts.Delimiter = " ";
    
    % Specify column names and types
    opts.PreserveVariableNames = true;
    opts.VariableNames = ["r11", "r12", "r13", "tx", "r21", "r22", "r23", "ty", "r31", "r32", "r33", "tz"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    opts.LeadingDelimitersRule = "ignore";
    
    % Import the data
    odom_data = readtable(filename, opts);
    
end